name: Build & Push Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build & Push Image
      run: 
          docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_PASS}}
          docker image build -t ${{secrets.DOCKERHUB_USER}}/weather_forecast:v1
          docker push ${{secrets.DOCKERHUB_USER}}/weather_forecast:v1

