name: Build & Push Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

    - name: Build Docker image
      run: docker image build -t ${{ secrets.DOCKERHUB_USER }}/weather_forecast:v1 .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USER }}/weather_forecast:v1
