name: Build & Push Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

    - name: Build Docker image
      run: docker image build -t ${{ secrets.DOCKERHUB_USER }}/weather_forecast:v1 .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USER }}/weather_forecast:v1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Start SSH agent and add SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Create .ssh directory
      run: mkdir -p ~/.ssh

    - name: Add WSL to known_hosts
      run: ssh-keyscan -H ${{ secrets.WSL_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to WSL
      run: |
        ssh user@${{ secrets.WSL_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKERHUB_USER }}/weather_forecast:v1
          docker stop weather_forecast || true
          docker rm weather_forecast || true
          docker run -d --name weather_forecast --restart always ${{ secrets.DOCKERHUB_USER }}/weather_forecast:v1
        EOF
