name: Build & Push Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

    - name: Build Docker image
      run: docker image build -t ${{ secrets.DOCKERHUB_USER }}/weather_forecast:v1 .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USER }}/weather_forecast:v1
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH_KEY" > id_rsa
        chmod 400 id_rsa

    - name: Add WSL to known_hosts
      run: ssh-keyscan -H ${{ secrets.WSL_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to WSL
      run: |
        ssh -i id_rsa user@${{ secrets.WSL_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKERHUB_USER }}/weather_forecast:v1
          docker run -d --name weather_forecast ${{ secrets.DOCKERHUB_USER }}/weather_forecast:v1
        EOF
